### ISSUE TITLE
Chrome webstore unavailable

### ISSUE THREAD

**Issue by CSmichaelnavara** [josh2112/url-rewriter#3]
Hello,
Your link from readme and from installed extension to Chrome webstore returns 404.
https://chrome.google.com/webstore/detail/url-rewriter/gpbblpbcnjdnnjdcdclojoonfmpoionh
Is it bug or feature? Do you remove this great tool from webstore purposely?

Michael Navara

**Comment by josh2112** [comment]
Hi Michael, it was taken off the web store because it no longer works. Chrome's event hooks definitions have changed a lot since I originally wrote the extension, and since I don't use it anymore I haven't kept it up-to-date.

Feel free to fork & fix it! And if you do, I'll link to your repo.

I updated the README to reflect the fact that it's no longer available on the store.

Thanks,
Josh
