### ISSUE TITLE
Just what I am looking for! - I think . .

### ISSUE THREAD

**Issue by philiprhoades** [josh2112/url-rewriter#4]
Josh,

I want to change this sort of URL:

https://www.youtube.com/watch?v=imdYIdv8F4w&list=PLjEaoINr3zgFX8ZsChQVQsuDSjEqdWMAD&index=4

to this:

https://www.youtube.com/watch_popup?v=imdYIdv8F4w&list=PLjEaoINr3zgFX8ZsChQVQsuDSjEqdWMAD&index=4

ie just insert "_popup" into the RegEx - would that have worked with url-rewriter before? - if not, I don't know JS but this seems like a nice little exercise to get started with - could you help me if I get stuck?

Thanks,
Phil.

**Comment by josh2112** [comment]
It would've, but... as I note in the README, I'm no longer maintaining this 8-year-old extension. Chrome's extension API has changed too much since then.

If you want to take a shot at getting it working, fork it and be my guest! But I'm sure there are other more up-to-date URL rewrite extensions in the Chrome store.
